const data = [
   {
      id: 1,
      name: "Wild Rider Layers Unisex Sneakers",
      price: 121,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/380697/02/sv01/fnd/IND/fmt/png/,Wild-Rider-Layers-Unisex-Sneakers",
      description:
         "With design elements inspired by the movement and motion of city life, the Wild Rider Layers Unisex Sneakers brings a fresh new dimension to the iconic Rider family. We've layered a rich mix of premium leather, suede and hairy suede onto a nylon upper to create texture and a raw edgy look that is pure street. The IMEVA midsole and rubber outsole ensure combined lightweight comfort and great traction to take you forward, further and faster through your day and beyond.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 2,
      name: "Mercedes Kart Cat-X Tech Unisex Sneakers",
      price: 151,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/306557/01/sv01/fnd/IND/fmt/png/Mercedes-Kart-Cat-X-Tech-Unisex-Sneakers",
      description:
         "Premium material and tech features are given a branded boost from German engineering. The Mercedes Kart Cat-X Tech Unisex Sneakers areleant style and esteem by Mercedes-AMG Petronas Motorsport. The piece rises to the occasion with an all-leather upper.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 3,
      name: "Jako Slip-On Men's Shoes",
      price: 161,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/381374/01/sv01/fnd/IND/fmt/png/Jako-Slip-On-Men's-Shoes",
      description:
         "The Jako Slip-On Men's Shoes are perfect for a laceless running style. Lightweight and styled for everyday wear, they feature a breathable and durable mesh upper. Layered cushioning adds comfort that goes the distance.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 4,
      name: "PUMA Serve Pro Lite Unisex shoes",
      price: 261,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374902/01/sv01/fnd/IND/fmt/png/PUMA-Serve-Pro-Lite-Unisex-Shoes",
      description:
         "Catering to the growing consumer expectation for casual, everyday comfort, the Serve Pro Lite Trainers feature shock-absorbing support for lightweight luxury.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 5,
      name: "Electron E Unisex Shoes",
      price: 321,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380435/04/sv01/fnd/IND/fmt/png/Electron-E-Unisex-Shoes",
      description:
         "There's more to the Electron E Trainers than meets the eye. Its visible technology highlights fantastic features like a breathable mesh upper, synthetic quarter panels for support and a bold aesthetic that's both fun and futuristic. The elastic band on the heel provides extra comfort.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 6,
      name: "one8 Virat Kohli Basket Classice Unisex Sneakers",
      price: 371,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/375314/01/sv01/fnd/IND/fmt/png/one8-Virat-Kohli-Basket-Classic-Unisex-Sneakers",
      description:
         "This one is for the collectors,connoisseur & extreme uber cool, the one8 Virat Kohli Basket Classic one8 V3 pays homage to the illustrious career of the legend himslef",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 7,
      name: "Caracal SoftFoam+Sneakers",
      price: 171,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/369863/18/sv01/fnd/IND/fmt/png/Caracal-SoftFoam+-Sneakers",
      description:
         "Long, clean lines, a premium leather upper and a tennis-inspired silhouette make the Caracal Sneakers your go-to for sleek style, whether you're on or off the court.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 8,
      name: "Mirage Mox Brightly Packed Shoes",
      price: 271,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/375168/01/sv01/fnd/IND/fmt/png/Mirage-Mox-Brightly-Packed-Shoes",
      description:
         "The Mirage Mox takes design cues from a 1970s pair of PUMA running shoes and transforms them with textural contrasts, pops of colour and funky futuristic elements. Inspired by illusions and the space between what's real and otherworldly, it's ready for new realities. Incorpo deconstructed approach to this season's trends, the Brightly Packed iteration features premium materials for a sophisticated silhouette that will have you rocking retro with cool confidence",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 9,
      name: "Future Rider Play On Unisex Sneakers",
      price: 571,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/371149/69/sv01/fnd/IND/fmt/png/Future-Rider-Play-On-Unisex-Sneakers",
      description:
         "Keep the game going in the shoe that launched a movement, our Future Rider Play On Unisex Sneakers. This shoe is dedicated to pared-down performance, featuring a super-light nylon, suede and leather upper and our famous shock-absorbing Federbein outsole to keep you pounding the pavement in style.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 10,
      name: "Anzarun Lite Unisex Sneakers",
      price: 671,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/371128/23/sv01/fnd/IND/fmt/png/Anzarun-Lite-Unisex-Sneakers",
      description:
         "The freshest look for any occasion, the Anzarun Lite Trainers are PUMA's most refined shoe yet. Featuring the breezy Anzarun DNA mesh upper, a cushy SoftFoam+ sockliner and discreet PUMA branding throughout, you're sure to look great, wherever the day takes you.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 11,
      name: "Pacer Next Cage Shoes",
      price: 371,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/365284/01/sv01/fnd/IND/fmt/png/Pacer-Next-Cage-Shoes",
      description:
         "With a foot-hugging mesh upper and a supportive lace-through midfoot caging system, the Pacer Next Cage has a sleek silhouette that is as ready for the gym as it is for the streets. A feather-light midsole provides superior energy return, cushioning and support, while slip-on construction adds a sock-like rather than a shoe-like feel. You wont want to leave home in anything else.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 12,
      name: "Rebound Lay-Up Lo SoftFoam+Mesh Shoes",
      price: 971,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/370914/01/sv01/fnd/IND/fmt/png/Rebound-Lay-Up-Lo-SoftFoam+-Mesh-Shoes",
      description:
         "Rethink the basketball trainer with the Rebound Lay-Up. This versatile sneaker features a mesh upper for superior breathability and a SoftFoam+ sockliner to give you a supportive fit. Paired with the iconic PUMA Formstrip, you will  have classic style with all of the innovation of today.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 13,
      name: "one8 Virat Kohli Basket Classic Unisex Sneakers",
      price: 451,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/375314/02/sv01/fnd/IND/fmt/png/one8-Virat-Kohli-Basket-Classic-Unisex-Sneakers",
      description:
         "This one is for the collectors,connoisseur & extreme uber cool, the one8 Virat Kohli Basket Classic one8 V3 pays homage to the illustrious career of the legend himslef",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 14,
      name: "PUMA x 1DER Columbus Men's Shoes",
      price: 271,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/387768/01/sv01/fnd/IND/fmt/png/PUMA-x-1DER-Columbus-Men's-Shoes",
      description:
         "Crafted for the ones who love an active life while looking stylish, PUMA and KL Rahul bring you the Columbus Men's Shoes. Enveloping KL Rahul's bold and sophisticated style, the contrasting overlays add edge to the overall look of PUMA x 1DER Columbus Men's Shoes. Even though the PUMA and 1DER logos are subtle, they are unmissable.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 15,
      name: "BMW M Motorsport City Rider Sneakers",
      price: 556,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/306975/01/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-City-Rider-Sneakers",
      description:
         "Live life grand with the BMW M Motorsport City Rider Unisex Sneakers. Featuring the signature Rider outsole in combination with the BMW branding. The stunning design adds the edge that'll make any casual look appear out of the world",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 16,
      name: "Jamming FUSEFIT Evolution Shoes",
      price: 771,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/366545/01/sv01/fnd/IND/fmt/png/Jamming-FUSEFIT-Evolution-Shoes",
      description:
         "Inspired by Spacewalk, the Jamming FUSEFIT Evolution Sneakers take the next step in futuristic design and technology. The combined outsole features a TPU membrane that encapsulates free-floating EVA beads for superior cushioning and the feeling of walking on sand. A unique lacing system gives you endless possibilities for comfort and style. With versatile and adaptive features, these sneakers are the perfect way to overcome any obstacle and propel yourself into new worlds.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 17,
      name: "Puma Perforated Low Men's Shoes",
      price: 871,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/372981/01/sv01/fnd/IND/fmt/png/Puma-Perforated-Low-Men's--IDP-Shoes",
      description: "Be street ready with the Puma Perforated Low Men's Shoes perfect for leisure and slaying around.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 18,
      name: "RS-X TOYS Unisex Sneakers",
      price: 971,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/369449/24/sv01/fnd/IND/fmt/png/RS-X-TOYS-Unisex-Sneakers",
      description:
         "Based on PUMAs innovative Running System technology, the RS-X line draws its design inspiration from the decade that had the best toys ever, hands down, bar none: the 1980s. Specifically, these RS-X TOYS Unisex Sneakers play on the trend of the toys of our childhood ultimately becoming collectors items down the road. The mesh upper on these Sneakers promote air flow, and features colours that would be at home in a crowded video arcade from 30 years ago. A unique cushioning function provides support, and the rubber outsole offers supreme traction and grip.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 19,
      name: "X-RAY² Ramble Unisex Shoes",
      price: 271,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/380727/06/sv01/fnd/IND/fmt/png/X-RAY%C2%B2-Ramble-Unisex-Shoes",
      description:
         "Take to the urban outdoors in the X-Ray² Ramble Trainers. PUMAs signature street style just got rugged, with technical fabrics like ripstop and suede, robust eyestay webbing straps and discreet branding. So, of course, the shoe looks fierce - but with the full-on comfort of Softfoam+, this hiking hybrid feels amazing too.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 20,
      name: "RS-X³ Twill Air Mesh Shoes",
      price: 171,
      discountPercentage: 10,
      image: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/368845/02/sv01/fnd/IND/fmt/png/RS-X%C2%B3-Twill-Air-Mesh-Shoes",
      description:
         "Dare to be bold. We've rebooted the RS design to take it to a whole new level. We've stripped it back to down basics and rebuilding it with more extreme mixes of colour and materials for a 3x stronger retro-meets-the-future look. PUMA's Running System is the engine under the bonnet, providing comfort and cushioning with every step.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 21,
      name: "Sl 20.2 Shoes",
      price: 871,
      discountPercentage: 10,
      image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/ad53e2abade1464bb0dcad0c00aaafec_9366/SL20.2_Shoes_Orange_Q46187_01_standard.jpg",
      description:
         "Dare to be bold. We've rebooted the RS design to take it to a whole new level. We've stripped it back to down basics and rebuilding it with more extreme mixes of colour and materials for a 3x stronger retro-meets-the-future look. PUMA's Running System is the engine under the bonnet, providing comfort and cushioning with every step.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 22,
      name: "ZX 2K Boost 2.0 Trail Shoes",
      price: 571,
      discountPercentage: 10,
      image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/06dcf7e2969045b48da6ad5500f501bf_9366/ZX_2K_Boost_2.0_Trail_Shoes_Green_GZ7784_01_standard.jpg",
      description:
         "The daily commute. The walk to the coffee shop. The off hours when you're free to roam. When life takes you out into the city, these adidas shoes help you cruise. Built on the innovative ZX line and infused with the technical vibe of trail shoes, they have a responsive Boost midsole, a grippy outsole and a warm lining. We're talking all-day comfort here.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 24,
      name: "PREDATOR FREAK .3 FG J",
      price: 1571,
      discountPercentage: 10,
      image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/ae95d399b7d446a4afd7ac7700d4d30d_9366/PREDATOR_FREAK_.3_FG_J_Black_FW7530_01_standard.jpg",
      description:
         "Dare to be bold. We've rebooted the RS design to take it to a whole new level. We've stripped it back to down basics and rebuilding it with more extreme mixes of colour and materials for a 3x stronger retro-meets-the-future look.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 25,
      name: "Defiant Generation multicourt tennis shoes",
      price: 971,
      discountPercentage: 10,
      image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/49a9781d4d9c46629e9dabad00dd154b_9366/Defiant_Generation_multicourt_tennis_shoes_Pink_FX5814_01_standard.jpg",
      description:
         "Who says you can't have it all? Lace up these adidas Defiant Generation tennis shoes to raise your game. The foot-hugging upper and cushioned midsole combine to keep you comfortable as you express yourself on the court. The durable outsole and abrasion-resistant toe easily stand up to your all-action game.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 26,
      name: "Air Jordan XXXVI Low",
      price: 126,
      discountPercentage: 10,
      image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/72d2a488-a065-47a1-bf66-e8adfe0ba1f7/air-jordan-xxxvi-low-mens-basketball-shoes-LgcvQl.png",
      description:
         "Lace up in the energy that sparked a basketball revolution. One of the lightest Air Jordan game shoes to date, the AJ XXXVI features a minimal but durable upper with reinforcing overlay. It also comes equipped with Zoom Air cushioning for added responsiveness. Step on to the court with the confidence that whatever you do—it's light work.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 27,
      name: "Air Jordan XXXVI Tatum",
      price: 200,
      discountPercentage: 10,
      image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ea16d7c4-7d1c-444c-bda7-1a4f32770935/air-jordan-xxxvi-tatum-mens-basketball-shoes-0jD1F6.png",
      description:
         "From the perimeter to the hoop, take the court with confidence. This is one of the lightest on-court Air Jordans to date, with a minimal-yet-durable upper reinforced with tough plastic details. Meanwhile, Zoom Air cushioning delivers energy return and elite responsiveness. The game asks for everything—now you have the shoes to match.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 28,
      name: "Air Jordan XXXVI 'Taco Jay'",
      price: 200,
      discountPercentage: 10,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6e348a2f-e547-479a-af13-38c624e7e9e8/air-jordan-xxxvi-taco-jay-mens-basketball-shoes-zv2DcC.png",
      description:
         "Prep for the game by lacing up your AJs, win the game by channeling the heat of “Taco Jay.” The 36th generation of Air Jordan celebrates the newest superstars to build the game, and this model is all about Jayson Tatum. Bridging tunnel style with performance tech, the design pays homage to Jay's intensity on the court—and fiery hot-sauce-and-cheese inspired colors nod to his favorite post-game food.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 29,
      name: "Air Jordan 7 Retro",
      price: 200,
      discountPercentage: 10,
      image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/bd3da02f-2ddc-4f0c-bb7b-f94c634cc0dd/air-jordan-7-retro-mens-shoes-7Zr804.png",
      description:
         "Inspired by the shoe originally worn by MJ during the '92 season and summer of basketball, the Air Jordan 7 Retro revives its championship legacy for a new generation of sneakerheads.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 30,
      name: "Air Jordan 1 Utility",
      price: 170,
      discountPercentage: 10,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/956b0723-ef2f-4b49-8982-e2ec37e14f9c/air-jordan-1-utility-mens-shoes.png",
      description:
         "Utilitarian, but make it edgy: these AJ1s give you functional use without compromising that style you know and love. Tough canvas, stash pockets and webbing pulls give these classic kicks a hit of rugged versatility.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },
   {
      id: 31,
      name: "Air Jordan 6 Retro",
      price: 200,
      discountPercentage: 10,
      image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/17fde102-11ef-4592-ad9a-795b667ed2cb/air-jordan-6-retro-shoes-vXk3FV.png",
      description:
         "MJ's sixth signature shoe debuted during the 1990-1991 season as His Airness battled rivals in pursuit of an elusive first championship. Now, it's back in a variety of color schemes. Gear up for the 30th anniversary of the Air Jordan 6 with this timeless classic.",
      quantity: 1,
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
   },

   {
      id: 32,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e4406f85-deaf-41fe-b030-c32fc9ac6b08/air-jordan-2-retro-j-balvin-shoes-QsTWbM.png",
      name: "Air Jordan 2 Retro Balvin",
      price: 400,
      color: "blue",
      quantity: 1,
      slug: "air-jordan-2-retro-balvin",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/16376cae-5d26-4432-ba6d-a40b1a34176c/air-jordan-2-retro-j-balvin-shoes-QsTWbM.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ff7855a5-f9a6-453d-b9b8-e76ab3108ebb/air-jordan-2-retro-j-balvin-shoes-QsTWbM.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/2c544b02-4a1d-4c87-a856-5d4afab489e1/air-jordan-2-retro-j-balvin-shoes-QsTWbM.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/5fa0562e-5d77-46e1-acb2-e2fcbd03812a/air-jordan-2-retro-j-balvin-shoes-QsTWbM.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/088f806f-f4c8-40ad-b7fa-c239d1806d9e/air-jordan-2-retro-j-balvin-shoes-QsTWbM.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/e7e3348d-562b-44be-b137-77fedf46de72/air-jordan-2-retro-j-balvin-shoes-QsTWbM.png",
         },
   
        
      ],
      description:
         "Like a breath of fresh air, this AJ2 refreshes its '86 design with plenty of energetic details and the sky's-the-limit style of the Prince of Reggaeton. Puffed-up panels on the upper and cloud graphics around the heel, collar and insole are paired with rainbow stitching accents and J Balvin's signature smiley face to steal the hearts of passers-by. Premium materials and Air cushioning in the heel will keep you dancing. And when the lights go out, you don't have to stop—just power up the tongue logo to let your glow-in-the-dark outsoles shine.",
      benefits: [
         { id: 1, text: "Nubuck leather feels soft and adds durability." },
         { id: 2, text: "Air-Sole unit in the heel delivers lightweight, responsive cushioning." },
         { id: 3, text: "Rubber outsole offers traction on a variety of surfaces." },
         { id: 4, text: "Colour Shown: Celestine Blue/Multi-Colour/White" },
         { id: 5, text: "Country/Region of Origin: Vietname" },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: {
         text: "Declaration of Importer: Direct import by the individual customer. Marketed by: Nike Global Trading B.V. Singapore Branch, 30 Pasir Panjang Road, #10-31/32, Mapletree Business City, Singapore 117 440",
      },
   },
   {
      id: 33,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d69697f5-91d5-4319-840e-80948cfd6a44/air-jordan-7-retro-sp-shoes-x5NMM9.png",
      name: "Air Jordan 7 Retro SP",
      price: 300,
      color: "red",
      quantity: 1,
      slug: "air-jordan-7-retro-sp",
      thumbnails: [
         {
            id: 1,
            name: "Air Jordan 7 Retro SP",
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/8c6c0164-318d-412c-8941-25f919fa7215/air-jordan-7-retro-sp-shoes-x5NMM9.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c764c759-31a5-498a-920a-0d1652bc4650/air-jordan-7-retro-sp-shoes-x5NMM9.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/74de07bb-6e0b-4e8c-b010-5e3d87546d01/air-jordan-7-retro-sp-shoes-x5NMM9.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/9868ce17-8b96-478a-8c59-2ef247789954/air-jordan-7-retro-sp-shoes-x5NMM9.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/2953e005-badb-4a5e-8abc-3733edba8eb2/air-jordan-7-retro-sp-shoes-x5NMM9.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b7dbeddc-dbdd-4f4a-8cd5-5e7d149c01dc/air-jordan-7-retro-sp-shoes-x5NMM9.png",
         },
       
        
      ],
      description:
         "Inspired by the game shoe worn by Mike throughout the '92 season, the latest iteration of the AJ7 revives its championship legacy for a new generation of sneakerheads. Come for the throwback style, stay all day for the premium construction and signature Air cushioning.",
      benefits: [
         { id: 1, text: "Full-length Nike Air technology provides lightweight cushioning." },
         { id: 2, text: "Leather and textile materials in the upper add durability." },
         { id: 3, text: "Rubber outsole gives your style traction." },
         { id: 4, text: "Colour Shown: Obsidian/Dark Obsidian/True Red/Metallic Gold" },
         { id: 5, text: "Country/Region of Origin: China" },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: {
         text: "Marketed by: Nike Global Trading B.V. Singapore Branch, 30 Pasir Panjang Road, #10-31/32, Mapletree Business City, Singapore 117 440",
      },
   },
   {
      id: 34,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/616a8a2f-193d-437c-b336-b4df8eacf0d3/air-jordan-1-mid-se-shoes-pZbfP8.png",
      name: "Air Jordan 1 Mid SE",
      price: 500,
      color: "red",
      quantity: 1,
      slug: "air-jordan-1-mid-se",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/4f2b31c3-e0d4-4895-b505-37782acd639d/air-jordan-1-mid-se-shoes-pZbfP8.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/bee8af25-08e4-4bbb-84e2-dfeda6a3f32a/air-jordan-1-mid-se-shoes-pZbfP8.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/0dc4bf49-d672-4d68-a36a-273bbfa0bde3/air-jordan-1-mid-se-shoes-pZbfP8.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/78a135b7-9923-4136-8908-53b7b003eeba/air-jordan-1-mid-se-shoes-pZbfP8.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/5efb6651-06bd-4933-bf78-ce983151a4fb/air-jordan-1-mid-se-shoes-pZbfP8.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f3784c19-9e21-4bd6-a968-b3855c80ca8e/air-jordan-1-mid-se-shoes-pZbfP8.png",
         },
       
       
      ],
      description:
         "Get that Jordan energy on your feet this festive season. Rich grain leather with bright details make this pair shine like festive lights.",
      benefits: [
         { id: 1, text: "Nike Air technology absorbs impact for cushioning with every step." },
         { id: 2, text: "Genuine and synthetic leather and textile upper for durability." },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: { text: "Declaration of Importer: Direct import by the individual customer" },
   },
   {
      id: 35,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1698d474-02df-4123-89c5-8630cdf54b4b/air-jordan-6-retro-shoes-fjwJgW.png",
      name: "Air Jordan 6 Retro",
      price: 200,
      color: "black",
      quantity: 1,
      slug: "air-jordan-6-retro",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b56de370-c5b8-43d3-bbd1-e9c44f4ed247/air-jordan-6-retro-shoes-fjwJgW.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/501955f6-b9cd-4889-ae44-b70f500724ff/air-jordan-6-retro-shoes-fjwJgW.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/296d6cb2-b2e2-42a7-9265-8661efcef918/air-jordan-6-retro-shoes-fjwJgW.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/4b5ae472-ff1e-4bfd-a47c-d46f73665a9e/air-jordan-6-retro-shoes-fjwJgW.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/285d16bf-dba4-4726-a62f-80b79f888fc3/air-jordan-6-retro-shoes-fjwJgW.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/20c63e08-c2e3-4e82-88b0-9f927782e2af/air-jordan-6-retro-shoes-fjwJgW.png",
         },
      
       
      ],
      description:
         "Championship vibes. MJ's 6th signature shoe debuted in '91—the year he earned his first ring—making the AJ6 an instant icon. This fresh take on the series-clinching classic has a sleek upper made from synthetic leather. Metallic accents add extra off-court flair, making these kicks your outfit MVPs.",
      benefits: [
         { id: 1, text: "Air-Sole unit and foam midsole cushion every step." },
         { id: 2, text: "Toggle lacing lets you easily adjust your fit." },
         { id: 3, text: "TColour Shown: Black/Black/Metallic Silver" },
         { id: 4, text: "Country/Region of Origin: Vietnam" },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: {
         text: "Declaration of Importer: Direct import by the individual customer Marketed by: Nike Global Trading B.V. Singapore Branch, 30 Pasir Panjang Road, #10-31/32, Mapletree Business City, Singapore 117 440",
      },
   },
   {
      id: 36,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/04984d02-3d67-40c4-a228-0ad69b65d2f2/air-jordan-xxxvii-rui-basketball-shoes-z63K2L.png",
      name: "Air Jordan XXXVII Rui",
      price: 300,
      color: "red",
      quantity: 1,
      slug: "air-jordan-xxxvii-rui",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1c5f57af-0ecd-4b06-b992-9bcb2af12886/air-jordan-xxxvii-rui-basketball-shoes-z63K2L.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1f28b81e-28a0-42ee-92b3-63e0750fc26b/air-jordan-xxxvii-rui-basketball-shoes-z63K2L.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/6ffe2ed0-db65-4f09-b720-191b7c6be104/air-jordan-xxxvii-rui-basketball-shoes-z63K2L.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/d86ed8f6-9dc7-47e7-9f8b-d25eca143180/air-jordan-xxxvii-rui-basketball-shoes-z63K2L.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/ed994ef8-93f6-43b2-8426-8682e40b1de1/air-jordan-xxxvii-rui-basketball-shoes-z63K2L.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/a7c1d400-6546-4d7c-a581-a1d3e53be98b/air-jordan-xxxvii-rui-basketball-shoes-z63K2L.png",
         },
       
        
      ],
      description:
         "You've got the hops and the speed—lace up in shoes that enhance what you bring to the court. The latest AJ is all about takeoffs and landings, with multiple Air units to get you off the ground and our signature Formula 23 foam to cushion your impact. Up top, you'll find layers of tough, reinforced leno-weave fabric that'll keep you contained—and leave your game uncompromised—no matter how fast you move.",
      benefits: [
         { id: 1, text: "Colours celebrate the on-court skills of Rui Hachimura." },
         { id: 2, text: "Top-line shape and Jordan Air on the tongue nod to the AJ7's iconic design." },
         { id: 3, text: "Upper design is a throwback to the exoskeleton style of the AJ7." },
         { id: 4, text: "Colour Shown: Siren Red/Flash Crimson/Armoury Navy/Sea Glass" },
         { id: 5, text: "Country/Region of Origin: Vietnam" },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: {
         text: "Declaration of Importer: Direct import by the individual customer ,Declaration of Importer: Direct import by the individual customer  ",
      },
   },
   {
      id: 37,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/47f3d481-4f86-4c1d-ae9e-17b8163bc530/luka-1-pf-basketball-shoes-4dv93M.png",
      name: "Luka 1 PF",
      price: 350,
      color: "red",
      quantity: 1,
      slug: "luka-1-pf",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/cdb92da2-e37d-4110-83ec-7f8883eae69d/luka-1-pf-basketball-shoes-4dv93M.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/2f0ebb41-38af-41b8-88ad-a7e1c1a7839e/luka-1-pf-basketball-shoes-4dv93M.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/0c3188f9-c07e-403d-b868-168030a1bb8d/luka-1-pf-basketball-shoes-4dv93M.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/2e2d9243-62a9-48c6-98cb-8f8e3d67616e/luka-1-pf-basketball-shoes-4dv93M.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/21c7d1f0-b000-4a3e-aafa-132822baa27e/luka-1-pf-basketball-shoes-4dv93M.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/44e64785-fb8e-4ca9-94c5-d523ab8e965b/luka-1-pf-basketball-shoes-4dv93M.png",
         },
        
       
      ],
      description:
         "Designed for No. 77 and made for every athlete craving speed and efficiency, Luka's debut delivers the goods. The first shoe with full-length Formula 23 foam, it has an ultra-supportive fit crafted with the step-back in mind. Meanwhile, strong and lightweight Flight Wire embroidery keeps you feeling contained, whether you're playing indoors or out. This is the assist you've been waiting for—get out there and make your shot. This version is designed wide and made for play on outdoor courts.",
      benefits: [
         { id: 1, text: "Colours celebrate the on-court skills of Rui Hachimura." },
         { id: 2, text: "Top-line shape and Jordan Air on the tongue nod to the AJ7's iconic design." },
         { id: 3, text: "Upper design is a throwback to the exoskeleton style of the AJ7." },
         { id: 4, text: "Colour Shown: Siren Red/Flash Crimson/Armoury Navy/Sea Glass" },
         { id: 5, text: "Country/Region of Origin: Vietnam" },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: {
         text: "Declaration of Importer: Direct import by the individual customer, Marketed by: Nike Global Trading B.V. Singapore Branch, 30 Pasir Panjang Road, #10-31/32, Mapletree Business City, Singapore 117 440",
      },
   },
   {
      id: 38,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/41e51f2a-7664-4f8b-9608-b047cea21b45/luka-1-pf-basketball-shoes-XTzWkj.png",
      name: "Luka 2 PF",
      price: 550,
      color: "blue",
      quantity: 1,
      slug: "luka-2-pf",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/64f3fca5-b422-40c2-a1be-6d0069e08208/luka-1-pf-basketball-shoes-XTzWkj.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/46e8eeb6-d132-4121-8470-953e9fe4c509/luka-1-pf-basketball-shoes-XTzWkj.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/99d9ae7f-26b2-45af-a4c3-3bcb5f554027/luka-1-pf-basketball-shoes-XTzWkj.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/3519c4a1-3b3b-4ba2-8107-83ae07218ce4/luka-1-pf-basketball-shoes-XTzWkj.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/7cbfcf4a-41b9-40e1-bd80-d24c4e141e1e/luka-1-pf-basketball-shoes-XTzWkj.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/0b7a426a-b08f-4347-9ea0-9d97c4ccbb06/luka-1-pf-basketball-shoes-XTzWkj.png",
         },
      
        
      ],
      description:
         "Designed for No. 77 and made for every athlete craving speed and efficiency, Luka's debut delivers the goods. The first shoe with full-length Formula 23 foam, it has an ultra-supportive fit crafted with the step-back in mind. Meanwhile, strong and lightweight Flight Wire embroidery keeps you feeling contained, whether you're playing indoors or out. This is the assist you've been waiting for—get out there and make your shot. This version is designed wider and made for play on outdoor courts.",
      benefits: [
         { id: 1, text: "Colours celebrate the on-court skills of Rui Hachimura." },
         { id: 2, text: "Top-line shape and Jordan Air on the tongue nod to the AJ7's iconic design." },
         { id: 3, text: "Upper design is a throwback to the exoskeleton style of the AJ7." },
         { id: 4, text: "Colour Shown: Siren Red/Flash Crimson/Armoury Navy/Sea Glass" },
         { id: 5, text: "Country/Region of Origin: Vietnam" },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: {
         text: "Declaration of Importer: Direct import by the individual customer, Marketed by: Nike Global Trading B.V. Singapore Branch, 30 Pasir Panjang Road, #10-31/32, Mapletree Business City, Singapore 117 440",
      },
   },
   {
      id: 39,
      image: "https://static.nike.com/a/images/t_PDP_864_v1,f_auto,q_auto:eco/4a44e41a-f17a-4036-b06b-b17e641d073f/air-jordan-legacy-312-shoes-8j5LzH.png",
      name: "Air Jordan Legacy 312",
      price: 650,
      color: "blue",
      quantity: 1,
      slug: "air-jordan-legacy-312",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/d93758d2-8a48-4fed-a951-8e63e94311a2/air-jordan-legacy-312-shoes-8j5LzH.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b1c175f7-733b-4ab1-9975-255b75b508a1/air-jordan-legacy-312-shoes-8j5LzH.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c0190a72-e860-4c3d-b926-26676257b34c/air-jordan-legacy-312-shoes-8j5LzH.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/5080f2ec-1d57-4fa7-8660-c1e291a87db4/air-jordan-legacy-312-shoes-8j5LzH.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b0e7fabd-a99b-4e08-9f2c-93197e012181/air-jordan-legacy-312-shoes-8j5LzH.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/4f30d377-fad6-4230-a2c0-8ba3d8b1373e/air-jordan-legacy-312-shoes-8j5LzH.png",
         },
       
      ],
      description:
         "The Legacy 312 was designed as a collage of iconic Air Jordan elements and this version is no different. What's new here are the colours: luminous, blooming jewel tones grounded in light neutrals. Sapphire and University Red come through big and bold, while Fossil Stone and Light Bone keep everything in check. And that speckled heel, with its multicolour mosaic? Now that's a detail to love.",
      benefits: [
         { id: 1, text: "The design combines iconic elements of the AJ 3, AJ 1 and Alpha Force." },
         { id: 2, text: "The leather and synthetic upper adds a midfoot strap for snug comfort." },
         { id: 3, text: "Visible Air-Sole unit at the heel enhances cushioning." },
         { id: 4, text: "Colour Shown: Sail/White/Fossil Stone/Concord" },
         { id: 5, text: "Country/Region of Origin: China" },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: { text: "Declaration of Importer: Direct import by the individual customer" },
   },
   {
      id: 40,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/037939bd-e08f-4c28-a3d2-b89c1578f7fc/jordan-stay-loyal-2-shoes-sDkgDk.png",
      name: "Jordan Stay Loyal 2",
      price: 250,
      color: "black",
      quantity: 1,
      slug: "jordan-stay-loyal-2",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/75de280b-a393-4b45-909f-777c77944cdd/jordan-stay-loyal-2-shoes-sDkgDk.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b4b5e6b7-5884-44c6-83b5-ae7ff38407c3/jordan-stay-loyal-2-shoes-sDkgDk.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/0e0a38c4-689e-4d98-be71-75a5d4b9b121/jordan-stay-loyal-2-shoes-sDkgDk.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/90be98ae-3dd5-48ef-8824-df7f198ee2d3/jordan-stay-loyal-2-shoes-sDkgDk.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/912adc2b-1ec7-470d-bfbb-bd14290ccaa5/jordan-stay-loyal-2-shoes-sDkgDk.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/d94105d6-c702-4da7-a3a3-4b2a01d60a06/jordan-stay-loyal-2-shoes-sDkgDk.png",
         },
        
      ],
      description:
         "Inspired by generations of Js, these kicks are a collage of cool. Design details recall decades of legendary shoes while paying homage to MJs storied career. Breathable mesh, sturdy leather and lightweight Air cushioning in the heel make it that much easier to walk in the footsteps of greatness.",
      benefits: [
         { id: 1, text: "Nike Air technology absorbs impact for cushioning with every step." },
         { id: 2, text: "Leather in the upper breaks in easily and makes for a long-lasting shoe." },
         { id: 3, text: "Knit mesh toe lets your feet breath." },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: { text: "Declaration of Importer: Direct import by the individual customer" },
   },
   {
      id: 41,
      image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/875b2ac6-0161-4d86-af23-df785e51f999/air-jordan-xxxvi-rui-basketball-shoes-JL99LQ.png",
      name: "Air Jordan XXXVI RUI",
      price: 650,
      color: "black",
      quantity: 1,
      slug: "air-jordan-xxxvi",
      thumbnails: [
         {
            id: 1,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/9dab9e2e-fc97-4006-bc7f-35921b5987a1/air-jordan-xxxvi-rui-basketball-shoes-JL99LQ.png",
         },
         {
            id: 2,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/3eab0201-c28f-425b-88e8-9451392252f5/air-jordan-xxxvi-rui-basketball-shoes-JL99LQ.png",
         },
         {
            id: 3,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/441ea555-67c9-4412-9067-ebb5766707bb/air-jordan-xxxvi-rui-basketball-shoes-JL99LQ.png",
         },
         {
            id: 4,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/989b5103-e5df-4abc-98ff-48555d8ace24/air-jordan-xxxvi-rui-basketball-shoes-JL99LQ.png",
         },
         {
            id: 5,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/2a9dac8a-e338-4750-a061-75b576e8f7da/air-jordan-xxxvi-rui-basketball-shoes-JL99LQ.png",
         },
         {
            id: 6,
            image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/9ad5d4f4-df01-424e-a228-a59539d06bee/air-jordan-xxxvi-rui-basketball-shoes-JL99LQ.png",
         },
       
      ],
      description:
         "From the perimeter to the hoop, take the court with confidence. This is one of the lightest Air Jordan game shoes to date, with a minimal but durable leno-weave upper reinforced with tough plastic details. Meanwhile, Zoom Air cushioning delivers energy return and elite responsiveness. The game asks for everything—now you have the shoe to match.",
      benefits: [
         { id: 1, text: "Nike Air technology absorbs impact for cushioning with every step." },
         { id: 2, text: "Leather in the upper breaks in easily and makes for a long-lasting shoe." },
         { id: 3, text: "Knit mesh toe lets your feet breath." },
      ],
      sizes: [
         { id: 1, size: "UK 3.5", is_available: true },
         { id: 2, size: "UK 4", is_available: false },
         { id: 3, size: "UK 4.5", is_available: true },
         { id: 4, size: "UK 5", is_available: true },
         { id: 5, size: "UK 5.5", is_available: true },
         { id: 6, size: "UK 6.5", is_available: true },
         { id: 7, size: "UK 7", is_available: true },
         { id: 8, size: "UK 7.5", is_available: true },
         { id: 9, size: "UK 8", is_available: false },
         { id: 10, size: "UK 8.5", is_available: true },
         { id: 11, size: "UK 9", is_available: true },
         { id: 12, size: "UK 9.5", is_available: true },
         { id: 13, size: "UK 10", is_available: false },
      ],
      product_information: { text: "Declaration of Importer: Direct import by the individual customer" },
   },
];

export default data;
